### PR TITLE
Upgrade build to use internal plugins 5.0.3

### PR DESCRIPTION
**Pull request by ilopmar**

### CODE REVIEW

**Comment by ilopmar** [comment]
The test `SyncCacheJavaSpec` in `cache-caffeine` module builds with this update. It seems the bean is not being created but I can't find out why. @sdelamo I could use your help and an extra pair of :eyes: here. :pray:

**Comment by sdelamo** [comment]
> The test `SyncCacheJavaSpec` in `cache-caffeine` module builds with this update. It seems the bean is not being created but I can't find out why. @sdelamo I could use your help and an extra pair of 👀 here. 🙏

The issue was `CounterService` was a Java class. I move them to `src/test/java` and added the `micronaut-inject-java` as test annotation processor.

**Comment by ilopmar** [comment]
I knew I was missing something. Probably in the previous versions of the internal plugins they were applying the appropriate "inject" modules (or maybe all of them).

Thanks for the help! :100:

**Comment by sdelamo** [comment]
I've [removed the retry plugin from settings.gradle](https://github.com/micronaut-projects/micronaut-cache/pull/386/commits/39f5ddd65ddcf351214c0eb7e8a35719a5c77afb). With the GE configuration, we already retry without the plugin in CI.

**Comment by sdelamo** [comment]
I have updated to 5.1.0 of build plugins and replaced <tt> in java doc wiht `@code`. Nonetheless, There are still a lot of javadoc warnings.

**Comment by ilopmar** [comment]
> I have updated to 5.1.0 of build plugins and replaced in java doc wiht `@code`. Nonetheless, There are still a lot of javadoc warnings.

I think @melix hasn't finished all his changes to remove all the warnings with the javadocs

**Review by sdelamo — APPROVED** [review]

**Comment by melix** [comment]
> I think @melix hasn't finished all his changes to remove all the warnings with the javadocs

The warnings were always there. Most likely you didn't see them because before the warnings depended on what version of Java you were using to build the javadocs. Now they consistently use Java 8 like on CI, which is why you get some probably. But I don't plan to suppress them, each project needs to fix them IMO.

**Comment by sdelamo** [comment]
> > I think @melix hasn't finished all his changes to remove all the warnings with the javadocs
> 
> The warnings were always there. Most likely you didn't see them because before the warnings depended on what version of Java you were using to build the javadocs. Now they consistently use Java 8 like on CI, which is why you get some probably. But I don't plan to suppress them, each project needs to fix them IMO.

I agree with @melix I think we have to fix them.

**Comment by sdelamo** [comment]
> > > I think @melix hasn't finished all his changes to remove all the warnings with the javadocs
> > 
> > 
> > The warnings were always there. Most likely you didn't see them because before the warnings depended on what version of Java you were using to build the javadocs. Now they consistently use Java 8 like on CI, which is why you get some probably. But I don't plan to suppress them, each project needs to fix them IMO.
> 
> I agree with @melix I think we have to fix them.

But lets do that in a separate PR. ;-[

**Comment by ilopmar** [comment]
Agree :)

**Pull request merged**
