### PR TITLE
feat: add thin client ignite to micronaut cache

### PR DESCRIPTION
**Pull request by pollend**
ref: #26
ref: #132

This implements the thin client for ignite. connecting to ignite with `Igniter.start` will search out for other nodes and make the application apart of the topology for the ignite cluster. A thin client on the other hand just connects and talks with the cluster. I'm think this could be split into two versions. (thick-client, thin-client). I'm not sure what the situation would entail using both a thin and thick client in this case?

### CODE REVIEW

**Comment by alvarosanchez** [comment]
@pollend I guess since the creation of the new `micronaut-ignite` project, this can be closed?

**Comment by ilopmar** [comment]
@pollend can you please confirm that we can close this in favor of `micronaut-ignite` project?

**Comment by pollend** [comment]
This can be closed

**Comment by ilopmar** [comment]
Thank you

**Pull request closed without merging**
