### PR TITLE
Fix cacheable called multiple times

### PR DESCRIPTION
**Pull request by ikovalyov**
This MR is based on https://github.com/micronaut-projects/micronaut-core/pull/2911/files . Resolved conflicts and fixed few issues.

This implementation works fine with `CompletableFuture` and `Flowable` types.

Unfortunately it doesn't support the `sync` types yet which is an issue in the Kotlin code. 

In Kotlin `suspend` functions returns `sync` types and should also be covered by this logic.

Please let me know what you think about this PR, I would be happy to make any required changes.

Thanks.

### CODE REVIEW

**Comment by ikovalyov** [comment]
@ilopmar @graemerocher @alvarosanchez  done
https://github.com/micronaut-projects/micronaut-core/pull/2911

**Comment by ikovalyov** [comment]
This MR works only with an `in-memory` cache and fails with other cache types for obvious reasons. I'll work on moving these changes to `in-memory` cache implementation instead of `CacheInterceptor`.

**Comment by ikovalyov** [comment]
@graemerocher I was thinking about this issue few days and it turned out it's not that easy to implement.

My first idea was to implement this workflow:


### Slow function result is cached
1. Cache get request comes in.
2. Cache missed.
3. Interceptor create a future of result and puts this future in the cache.
4. New cache request comes in.
5. There is a future in the cache.
6. Interceptor returns this future, no new invocations.
7. Original future is completed.
    1. Result is put in the cache.
    2. Future of result is removed from the cache.


### Fast function result is cached
1. Cache get request comes in.
2. Cache missed.
3. Interceptor create a future of result and puts this future in the cache.
4. Original future is completed.
    1. Result is put in the cache.
    2. Future of result is removed from the cache.
5. New cache request comes in.
5. There is a result in the cache.
6. Completed future with result is returned.

The actual code is slightly more complicated to solve some race condition issues and result type conversion issues. And it works fine with in-memory cache.

Unfortunately it will never work with other cache types which are serialising data (as Future is not serialisable for obvious reasons). Please note that same logic can be emulated even without need of future serialisation.

For example we can put some temporary value with timeout in the cache and instead of launching another parallel execution just check this value until it will be updated to the actual function call result. But that's too much for this MR. And should not be enabled by default.

But still I have issues with the default SyncCache. It means I need to implement cache-specific behaviour in the `CacheInterceptor` and that's something which doesn't look like a good decision.

Another approach is to refactor the CacheInterceptor and move logic related to the getting and putting data into the Cache implementation. Then by default all caches will have current functionality but if needed we'll be able to override it.

So here is my proposal:
- CacheInterceptor has 2 different functions right now: `interceptSync` and `interceptAsCompletableFuture`. I would like to merge them into 1 function as preparation step.
- Create a `CacheService` class which will do the cache manipulation done by cache interceptor right now
- Create a factory which returns different cache services depending on which cache is used
- Create a `CaffeineCacheService` which will implement logic from this MR.

That's a lot to do and probably should be split into multiple MR's. Or probably it conflicts with your current development plan. Or that's something you don't want to be in the Micronaut codebase. Please let me know your thoughts.

Thanks.

**Comment by mattwelke** [comment]
> Unfortunately it will never work with other cache types which are serialising data (as Future is not serialisable for obvious reasons). Please note that same logic can be emulated even without need of future serialisation.

For example we can put some temporary value with timeout in the cache and instead of launching another parallel execution just check this value until it will be updated to the actual function call result. But that's too much for this MR. And should not be enabled by default.

@ikovalyov I notice this pull request is closed. Did you ever get around to creating those separate pull requests you describe? I have this use case. I have cache get operations that take a few seconds and put a lot of stress on the backing service used when the cache get operation is a miss. I could solve this by preventing parallel requests from happening in case of a miss.

Using in-memory caching, which you say would be easy to implement, would work if I were okay running just one process. But we use Kubernetes in production and always keep a minimum of two pods running to protect us from unavailability due to a potential crash. Using a shared cache (like Redis) would help us with this. I thought of making some custom caching logic with the redlock algorithm, but it sounds like you already had some thoughts on how to do it in a way that kept as much logic as possible within the Micronaut framework.

**Comment by ikovalyov** [comment]
Hi @mattwelke .
I ended up with writing a cache wrapper outside of the micronaut to fix this issue. It's ok for us to use a memory cache as same requests will always go to the same machine so wrapper is really a simple class which would become very complicated if you need it to store its state on external service.
Thanks.

**Comment by mattwelke** [comment]
@ikovalyov Funny you mention that. I also ended up doing a workaround. I explored the idea last night and was able to come up with what I think is an elegant solution. I use two beans together. One bean uses Redisson's Redlock feature to synchronize the business logic such that only one process is doing it at a time, and the bean it depends on uses built in Micronaut Redis caching to store the results. Put together, it works for my use case where I don't want more than one pod attempting the operation at a time when the cache expires. The pod attempting it gives up the lock automatically when it's done, at which the other pods are free to pull the cached results out of Redis.

Example repo: https://github.com/mattwelke/redlock-redis-cache-test

Bean for synchronizing business logic: https://github.com/mattwelke/redlock-redis-cache-test/blob/master/src/main/java/com/mattwelke/BooksServiceUnsynchronized.java
Bean for doing the business logic, with Micronaut caching: https://github.com/mattwelke/redlock-redis-cache-test/blob/master/src/main/java/com/mattwelke/BooksService.java

**Pull request closed without merging**
