### PR TITLE
Adds support for Coherence caching

### PR DESCRIPTION
**Pull request by vasac**

### CODE REVIEW

**Comment by alvarosanchez** [comment]
I thought we were working on a micronanut-coherence repo?

**Comment by vasac** [comment]
We do. Should I move it there?

**Comment by graemerocher** [comment]
Yeah I guess it can live there. The same arrangement exists for ignite (see https://github.com/micronaut-projects/micronaut-ignite)

**Comment by graemerocher** [comment]
We can maybe keep the documentation part on the PR and include it in the cache docs once the coherence module is out

**Comment by alvarosanchez** [comment]
I think the documentation should be co-located with the code

**Comment by graemerocher** [comment]
@alvarosanchez I am more talking about discoverability. If people come to the cache docs looking for caching and there is no reference to the fact that coherence is supported that is a shame. It doesn't have to be the entire documentation just something that says coherence is supported and here is where you can find the docs

**Comment by alvarosanchez** [comment]
Right, that I agree with. It's what we do with Redis, for example.

**Comment by vasac** [comment]
👍  I'm moving this to `micronaut-coherence`

**Pull request closed without merging**
