### PR TITLE
WIP: feat: add ignite to micronaut cache

### PR DESCRIPTION
**Pull request by pollend**
ref: https://github.com/micronaut-projects/micronaut-cache/issues/26

### CODE REVIEW

**Comment by pollend** [comment]
the basic implementation seems to working correctly. I'm now working on adding some more test cases.

**Comment by pollend** [comment]
I'm finding that the configuration is fairly extensive. Not entirely sure how this should be approached. I'm not entirely sure how to deal with it all. I have a bare minimum working configuration, but I'm not entirely sure what should or shouldn't be included.

**Comment by alvarosanchez** [comment]
Micronaut's `@ConfigurationBuilder` can help here, however, it should be more customised.

You can run `./gradlew docs` and see the generated configuration reference. Note that by default,  it picks all setters, however many of them aren't really usable in a configuration file without a converter, eg:

image

So those should be excluded, leaving just the basic types.

Also, I see that `org.apache.ignite.configuration.IgniteConfiguration` can be enhanced with some other configuration classes, like `ClientConnectorConfiguration`. Instead of replicating them with nested `@ConfigurationProperties` classes, you should define Ignite's configuration with `@ConfigurationBuilder(value = "nested-key", ...)`, and then provide a method that builds the `IgniteConfiguration` by passing all the instances of the children configuration classes. Have a look at https://github.com/micronaut-projects/micronaut-cache/blob/master/cache-infinispan/src/main/java/io/micronaut/cache/infinispan/InfinispanHotRodClientConfiguration.java for an example that takes the same approach

**Comment by pollend** [comment]
Is there any plans to allow ConfigurationBuilder to accept multiple classes to implement from. The implementation I came up with seems kind of cumbersome. 
 
```
prop:
  impl-class: TcpDiscoverySharedFsIpFinder
  p1: a1
  p2: a2 
```

**Comment by alvarosanchez** [comment]
Regarding `ConfigurationBuilder`, I don't quite get what you mean.

Regarding the clients, does it really make sense for an application to have multiple client configurations? Is it not the case that an application would have a single client (either thin or thick)? And which type is the most likely to be used?

**Comment by pollend** [comment]
The amount of configuration is pretty extensive and it seems pretty difficult to try and cover all the use cases. The bare implementation doesn't seem too useful and anything outside of this would be easier to implement through providing a Bean. At a minimum it could just provide a factory that produces an instance of SyncCache with `Ignite`.

I have the PR #133 that just implements the thin-client. The thin-client is basically complete without much else to add. I'm not sure how to continue with this PR with how extensive the library is.

**Comment by graemerocher** [comment]
Thanks we will take it from here

**Comment by schernolyas** [comment]
Hi!
What is status of the PR ?

**Comment by graemerocher** [comment]
The status is that we have a feature freeze for 2.0 and once Micronaut 2.0 is out (next week Friday) we will merge and incorporate into the next release

**Comment by schernolyas** [comment]
Hi @graemerocher ! 
Thank you very much! It is possible, that I will need to develop Micronaut Data for Apache Ignite.  Where can I find a information about implementation of new modules for Micronaut Data?

**Comment by pollend** [comment]
Hi @schernolyas,

All the modules are public so you can probably start from there and if you have specific questions you can probably find the answers in the [gitter](https://gitter.im/micronautfw/).

**Comment by schernolyas** [comment]
Hi @pollend , @graemerocher , @alvarosanchez !

I am going on with my investigation with Micronaut. For my project, I will need to develop HTTP session store and data (micronaut data) in Apache Ignite/GridGain Community Edition. Also I have found project https://github.com/micronaut-projects/micronaut-redis. This project (I mean "micronaut-redis") has features for module "micronaut-cache" and "micronaut-session".
My first target is develop code to store http sessions in Ignite. Where do I need to develop it? And I see next ways:
1. It is new module like module for redis which has dependency to the module (with @pollend 's code :-) )
2. We gather all Apache Ignite-linked code  in new module (micronaut-ignite)

What is the best way?
yes, may it is not the best place for the discuss but ... all interested parties are here.

@pollend  the code is able to pass native compilation, isn't it? I discussed with Ignite developer team and they recommended to use Ignite thin client (https://apacheignite.readme.io/docs/java-thin-client). Because they doubt that a Ignite server is able to pass native compilation to work in GraalVM.

**Comment by graemerocher** [comment]
Best way is to setup a new project. I can help with that on Monday. Do you want it called micronaut-ignite?

As for GraalVM, changes to ignite may be necessary. We would need to conduct testing once the modules are ready. We have a separate integration test suite for Graal native

**Comment by pollend** [comment]
@schernolyas you can look here for the thin client https://github.com/micronaut-projects/micronaut-cache/pull/133. Any work on this pr should live in it's own module. I realized that core ignite is a bit much for a cache module like this.

**Comment by schernolyas** [comment]
> @schernolyas you can look here for the thin client #133. Any work on this pr should live in it's own module. I realized that core ignite is a bit much for a cache module like this.
> 
> My plan is to have #133 merged and then have another plan for adding core ignite.

Yes, @pollend , I have seen the PR (#133 ).  What do you think about the idea to produce module "micronaut-ignite" and gather all features at the module?

**Comment by pollend** [comment]
That would be for the best. Would the thin client work in the default cache module? Or would that get moved?

**Comment by schernolyas** [comment]
> That would be for the best. Would the thin client work in the default cache module? Or would that get moved?

I prefer to get a opinion of @graemerocher because he is author of the framework :-)

**Comment by graemerocher** [comment]
A dedicated ignite module makes sense to me

**Comment by schernolyas** [comment]
@pollend 

May be ... we will discuss about Apache Ignite integration. I will have a skype meeting with @graemerocher  on Monday. Do you want to get part ?

**Comment by schernolyas** [comment]
@pollend and @graemerocher 
I propose that #132 and #133 would be merged to the project and marked as experimental. I will copy the code from these PRs to new module "micronaut-ignite" and append feature with storing http sessions.  Is it acceptable plan?

**Comment by graemerocher** [comment]
Sounds good

**Comment by pollend** [comment]
I can be available on Monday for a short Skype meeting.

**Comment by schernolyas** [comment]
> I can be available on Monday for a short Skype meeting.

Central European time.  How about 3pm central?  Could you send your Skype account to my email (sergey.chernolyas@gmail.com) if you will take a part at the meeting?

**Comment by alvarosanchez** [comment]
Same as https://github.com/micronaut-projects/micronaut-cache/pull/133#issuecomment-664301476

**Comment by ilopmar** [comment]
@pollend can you please confirm that we can close this in favor of `micronaut-ignite` project?

**Comment by pollend** [comment]
This can be closed.

**Comment by ilopmar** [comment]
Thanks!

**Pull request closed without merging**
